### ISSUE TITLE
Why no export or default rules?

### ISSUE THREAD

**Issue by ernstnaezer** [retyped/chartist-tsd-ambient#1]
Hi there,

I'm trying to use `chartist`, `typescript` and `jspm` together. However when I do so I am greeted by an error that the `Chartist` variable can not be found. This makes sense since the package javascript isn't loaded.

The only way I can get it to load is either by including from the CDN or by adding the following lines to the bottom of the `tsd` file:

```
declare module 'chartist' {
    export = Chartist
} 
```

and 

```
import * as Chartist from 'chartist'
```

Any thoughts on how I can make `jspm` import this library? Or should the export be in the type definitions?

**Comment by shyiko** [comment]
Hi. Yeah, "declare module 'chartist' ..." is definitely missing in chartist.d.ts (all type definitions under retyped/ were migrated from DefinitelyTyped in automated manner so incomplete d.ts are expected (given quality of DefinitelyTyped typings)). 
If you have a change ready - I'd be happy to merge PR in.

**Comment by ernstnaezer** [comment]
Here we go... thanks

**Comment by shyiko** [comment]
:+1:  Thank you!

**Comment by shyiko** [comment]
0.9.4-1
